# Householder-Transformation schrittweise

In [1]:
import numpy as np
from numpy.linalg import norm

Die allgemeine Schreibweise der Householder-Transformation für einen beliebigen Vektor $w$ ist gegeben durch
\begin{equation}\label{eq:householdertransformation}H(w) = \text{id} - 2\,\frac{w\cdot w^T}{\langle w, w\rangle}
\end{equation}
wobei $w\cdot w^T$ das Kroneckerprodukt
$$w\cdot w^T = (w_i\,w_j)_{i,j=1\ldots m}\in\mathbb{R}^{m\times m}$$
sei.

In [9]:
# Selber implementieren
def HouseholderTransformation(w):
    Im = np.eye((len(w)))
    x = w[:,0]
    x_norm = norm(x)
    sgn = mysign(w[0,0])
    e_1 = e(len(w))

    v = x + (sgn * x_norm) * e_1

    #print("Erster Vektor: ", x, x_norm, "\tSGN: ",sgn, w[0,0], "e1: ", e_1, v)

    v_t_v = v.T @ v
    v_v_t = np.outer(v,v) # v mal v.T rechnen
    #print("V: ",np.absolute(w))

    H = Im - ((2* v_v_t) /  v_t_v)
    #print("Im: ", Im)
    #print(v_t_v, v_v_t)
    #print("H:", H)
    return H


Gesucht ist der geeignete Normalenvektor so, dass der gespiegelte Spaltenvektor auf die $e_1$ Achse zu liegen kommt. Sei mit $y$ der Spaltenvektor bezeichnet, so kann man zeigen (siehe Skript), dass der Vektor
\begin{equation}
w = y \pm \|y\|_2 e_1
\end{equation}
die gewünschte Eigenschaft hat. Um **Auslöschung** in der Berechnung von $w$ zu vermeiden, wählt man
\begin{equation}
w = y + \text{sign}(y_1) \|y\|_2 e_1
\end{equation}
mit
\begin{equation}
\text{sign}(s) = \begin{cases} 1 & \quad \text{für} s \ge 0\\ -1 & \quad \text{sonst}.\end{cases}
\end{equation}

In [3]:
def mysign(x): # numpy sign liefert 0 für 0
    if x >= 0:
        return 1
    else:
        return -1

Funktion für den n-dimensionalen Einheitsvektor

In [4]:
def e(n):
    return np.array([1]+[0 for k in range(n-1)])

Mit Hilfe der Householder-Transformation soll nun die Matrix $A$ in eine orthogonale Matrix $Q$ und reguläre obere Dreiecksmatrix $R$ zerlegt werden. Im Beispiel wählen wir eine zufällige Matrix $A \in \mathbb{R}^{10\times5}$.

In [7]:
A = np.array([[-1,  7, -8, -9,  6],
       [-6, -8,  0,  3,  8],
       [-4, -2,  8,  0, -2],
       [-1, -9,  4, -8,  2],
       [-3, -5, -5,  7, -4],
       [-7, -4,  7, -1,  5],
       [-9, -7,  6, -5, -8],
       [-4, -3, -5,  3, -6],
       [ 5,  7,  5, -4, -5],
       [ 4, -6, -8, -2, -5]],dtype=float)
m,n = A.shape
A2 = A.copy()

### Householder Transformation, Alle Spalten

Wir automatisieren nun den Prozess und überschreiben die Submatrizen der Matrix $A_1$ sukzessive:

In [10]:
Q = np.eye((m))
#print(A1)


for k in range(0,n-1):
    print('Spalte '+str(k+1))
    w = A[k:,k:]
    #print("Hypermatrix: ", w)
    Qk = HouseholderTransformation(w)
    #print(Qk)
    A[k:,k:] = Qk@A[k:,k:]
    H_j = np.eye((m))
    H_j[k:,k:] = Qk
    Q = H_j@Q
    #print("R:", np.round(A,4))


print("R:", np.round(A,2))
print("Q:", np.round(Q,2).T)
print("Q*R:", np.round(Q.T @ A,2))


Q,R = np.linalg.qr(A2)

print("Loesung")
print(np.round(Q,2), np.round(R,2))
print("L: Q*R:", np.round(Q.dot(R),2))

Spalte 1
Spalte 2
Spalte 3
Spalte 4
R: [[-15.81 -11.83   6.51   0.63   1.26]
 [ -0.   -15.56  -1.42   1.83  -3.08]
 [  0.    -0.    17.99  -2.92  -0.92]
 [ -0.    -0.    -0.   -15.68   1.59]
 [  0.    -0.     0.     0.    -5.77]
 [  0.    -0.    -0.    -0.     3.39]
 [  0.    -0.    -0.    -0.   -11.31]
 [  0.    -0.     0.     0.    -8.27]
 [ -0.     0.     0.    -0.    -1.97]
 [  0.     0.     0.     0.    -6.29]]
Q: [[-1. -0. -0. -0.  0.  0.  0.  0. -0. -0.]
 [ 0. -1.  0.  0. -0. -0. -0. -0.  0.  0.]
 [ 0. -0. -1. -0. -0.  0.  0. -0.  0. -0.]
 [ 0. -0.  0. -1.  0. -0. -0.  0. -0.  0.]
 [ 0. -0. -0.  0.  1.  0. -0. -0.  0. -0.]
 [ 0. -0.  0. -0.  0.  1. -0.  0.  0.  0.]
 [ 0. -0.  0. -0. -0. -0.  1. -0.  0.  0.]
 [ 0. -0. -0.  0. -0.  0. -0.  1.  0. -0.]
 [-0.  0.  0. -0.  0.  0.  0.  0.  1.  0.]
 [-0.  0. -0.  0. -0.  0.  0. -0.  0.  1.]]
Q*R: [[ 15.81  11.83  -6.51  -0.63  -1.26]
 [ -0.    15.56   1.42  -1.83   3.08]
 [ -0.     0.   -17.99   2.92   0.92]
 [ -0.    -0.     0.    15.

### Q, R berechnen

- Berechnen sie abschliessend $Q,R$ so, dass $Q\cdot R = A$ gilt.
- Vergleichen Sie Ihr Resultat mit der Funktion von NumPy.

In [14]:
Q,R = np.linalg.qr(A2)

In [15]:
Q.shape

(10, 5)

In [16]:
R.shape

(5, 5)

Frage: Warum reicht diese reduzierte $Q$ und $R$ Matrix?

Die letzte Spalte der R-Matrix  ist die einzige welche ab zeile 5 noch einträge hat.
Diese Einträge ,ab Zeile 5, können zusammengefasst werden und in Xn,n gespeichert werden.
Für die Matrix Q gilt alle Einträge ab Spalte 5 können zusammengefasst werden.