# FTCS

In [3]:
import numpy as np
import matplotlib.pyplot as plt


a = 3.8*10**-6    # Temperaturleitfähigkeit in m^2/s
Tr =100
Tl = 0            # Temperatur



A1 = np.zeros((J, J))
 
for i in range(0,J-1):
    A1[i,i] = -2
    A1[i+1,i] = 1
    A1[i,i+1] = 1
A1[J-1,J-1] = -2
A1[J-1,J-2] = 2
print(A1)
 
v = np.zeros(J)
v[0] = Tl/h**2
v[J-1] = Tr/h**2


print(A1)


[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
